<?php

function algus_pass_theme($existing, $type, $theme, $path)
{
  return [
    'folders_list' => [
      'variables' => [
        'content' => []
      ]
    ],
    'pass_list' => [
      'variables' => [
        'content' => [],
        'variables' => []
      ]
    ],
    'pass_entity' => [
      'variables' => [
        'content' => [],
        'variables' => []
      ]
    ]
  ];
}

//Хук для того чтобы автоматически устанавливать поле Компания в термине таксономию(значение брать из Компании пользователя кто создаёт термин)
function algus_pass_taxonomy_term_presave($term) {

  //Машинное название таксономии
  $taxonomy_name = 'taxonomy_folders';
  $current_user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  //Достаём компанию текущего юзера
  $company = $current_user->get('field_company')->target_id;
  if($company){
    if ($term->bundle() == $taxonomy_name) {
      //Устанавливаем в термине значение поля Company равным компании из объекта текущего пользователя друпал
      $term->set('field_company', $company);
    }
  }
}

function algus_pass_preprocess_page(&$vars) {
  //custom logic of when to include the library
  // ....
  $vars['#attached']['library'][] =  'core/drupal.dialog.ajax';
}

//Хук для того чтобы изменить запрос индекс Search Api
function algus_pass_search_api_query_alter(\Drupal\search_api\Query\QueryInterface $query) {
  // Проверяем, что индекс называется "passwords".
  if ($query->getIndex()->id() === 'passwords') {
    $user = \Drupal::currentUser();

    $ids = \Drupal::database()
      ->select('pass_access', 'p')
      ->fields('p', ['entity_id'])
      ->condition('p.entity_type', 'node') // <--
      ->condition('p.user_id', $user->id()) // <--
      ->execute()->fetchCol();

    // Добавьте условие к запросу.
    $query->addCondition('id', $ids, 'IN');

  }
}
